<?php
/**
 * This file is part of OpenClinic
 *
 * Copyright (c) 2002-2006 jact
 * Licensed under the GNU GPL. For full terms see the file LICENSE.
 *
 * $Id: index.php,v 1.6 2006/03/15 20:12:41 jact Exp $
 */

/**
 * index.php
 *
 * Summary page of the Admin tab
 *
 * Author: jact <jachavar@gmail.com>
 */

  /**
   * Controlling vars
   */
  $tab = "admin";
  $nav = "summary";

  require_once("../shared/read_settings.php");
  require_once("../shared/login_check.php");

  /**
   * Show page
   */
  $title = _("Admin");
  require_once("../shared/header.php");
?>

<h1 class="bigIcon adminIcon">
  <?php echo $title; ?>
</h1>

<p><?php echo _("Use the following functions located in the left hand navigation area to manage your clinic's staff and administrative records."); ?></p>

<h2 class="icon configIcon">
  <a href="../admin/setting_edit_form.php"><?php echo _("Config settings"); ?></a>
</h2>

<p><?php echo _("Update config settings."); ?></p>

<hr />

<h2 class="icon themeIcon">
  <a href="../admin/theme_list.php"><?php echo _("Themes"); ?></a>
</h2>

<p><?php echo _("View the list of site look and feel themes."); ?> <?php echo _("From this list you can:"); ?></p>

<ul>
  <li><?php echo _("set the theme in use by default for your site"); ?></li>
  <li><?php echo _("build a new site theme"); ?></li>
  <li><?php echo _("edit an existing theme"); ?></li>
  <li><?php echo _("delete a theme"); ?></li>
</ul>

<hr />

<h2 class="icon staffIcon">
  <a href="../admin/staff_list.php"><?php echo _("Staff Members"); ?></a>
</h2>

<p><?php echo _("View the clinic staff member list."); ?> <?php echo _("From this list you can:"); ?></p>

<ul>
  <li><?php echo _("build a new staff member"); ?></li>
  <li><?php echo _("edit the staff member information"); ?></li>
  <li><?php echo _("build or edit the clinic user associated"); ?></li>
  <li><?php echo _("delete a staff member"); ?></li>
</ul>

<hr />

<h2 class="icon userIcon">
  <a href="../admin/user_list.php"><?php echo _("Users"); ?></a>
</h2>

<p><?php echo _("View the list of clinic users."); ?> <?php echo _("From this list you can:"); ?></p>

<ul>
  <li><?php echo _("build a new clinic user"); ?></li>
  <li><?php echo _("edit a existing clinic user"); ?></li>
  <li><?php echo _("edit the staff member information"); ?></li>
  <li><?php echo _("reset a user's password"); ?></li>
  <li><?php echo _("delete a clinic user"); ?></li>
</ul>

<hr />

<h2 class="icon dumpIcon">
  <a href="../admin/dump_view_form.php"><?php echo _("Dumps"); ?></a>
</h2>

<p><?php echo _("From this option you can:"); ?></p>

<ul>
  <li><?php echo _("install dump from file"); ?></li>
  <li><?php echo sprintf(_("export database dump to %s format"), "MySQL"); ?></li>
  <li><?php echo sprintf(_("export database dump to %s format"), "XML"); ?></li>
  <li><?php echo sprintf(_("export database dump to %s format"), "CSV"); ?></li>
  <li><?php echo _("optimize database"); ?></li>
</ul>

<hr />

<h2 class="icon logIcon">
  <a href="../admin/log_stats.php"><?php echo _("Logs"); ?></a>
</h2>

<p><?php echo _("View logs generated by the program:"); ?></p>

<ul>
  <li><?php echo _("user's accesses logs"); ?></li>
  <li><?php echo _("operations with medical records logs"); ?></li>
  <li><?php echo _("statistics for years, months, days and hours"); ?></li>
</ul>

<?php require_once("../shared/footer.php"); ?>
