<?php
/**
 * @package OpenClinic
 *
 * @copyright Copyright (c) 2002-2006 jact
 * @license Licensed under the GNU GPL. For full terms see the file LICENSE.
 *
 * $Id: index.php,v 1.7 2006/03/24 20:17:16 jact Exp $
 */

/**
 * index.php
 *
 * Summary page of the Admin tab
 *
 * @author jact <jachavar@gmail.com>
 */

  /**
   * Controlling vars
   */
  $tab = "admin";
  $nav = "summary";

  require_once("../shared/read_settings.php");
  require_once("../shared/login_check.php");

  /**
   * Show page
   */
  $title = _("Admin");
  require_once("../shared/header.php");

  echo '<h1 class="bigIcon adminIcon">' . $title . "</h1>\n";
  echo '<p>' . _("Use the following functions located in the left hand navigation area to manage your clinic's staff and administrative records.") . "</p>\n";

  echo '<h2 class="icon configIcon">' . HTML::strLink(_("Config settings"), '../admin/setting_edit_form.php') . "</h2>\n";
  echo '<p>' . _("Update config settings.") . "</p>\n";

  echo "<hr />\n";

  echo '<h2 class="icon themeIcon">' . HTML::strLink(_("Themes"), '../admin/theme_list.php') . "</h2>\n";
  echo '<p>' . _("View the list of site look and feel themes.") . ' ' . _("From this list you can:") . "</p>\n";

  echo "<ul>\n";
  echo '<li>' . _("set the theme in use by default for your site") . "</li>\n";
  echo '<li>' . _("build a new site theme") . "</li>\n";
  echo '<li>' . _("edit an existing theme") . "</li>\n";
  echo '<li>' . _("delete a theme") . "</li>\n";
  echo "</ul>\n";

  echo "<hr />\n";

  echo '<h2 class="icon staffIcon">' . HTML::strLink(_("Staff Members"), '../admin/staff_list.php') . "</h2>\n";
  echo '<p>' . _("View the clinic staff member list.") . ' ' . _("From this list you can:") . "</p>\n";

  echo "<ul>\n";
  echo '<li>' . _("build a new staff member") . "</li>\n";
  echo '<li>' . _("edit the staff member information") . "</li>\n";
  echo '<li>' . _("build or edit the clinic user associated") . "</li>\n";
  echo '<li>' . _("delete a staff member") . "</li>\n";
  echo "</ul>\n";

  echo "<hr />\n";

  echo '<h2 class="icon userIcon">' . HTML::strLink(_("Users"), '../admin/user_list.php') . "</h2>\n";
  echo '<p>' . _("View the list of clinic users.") . ' ' . _("From this list you can:") . "</p>\n";

  echo "<ul>\n";
  echo '<li>' . _("build a new clinic user") . "</li>\n";
  echo '<li>' . _("edit a existing clinic user") . "</li>\n";
  echo '<li>' . _("edit the staff member information") . "</li>\n";
  echo '<li>' . _("reset a user's password") . "</li>\n";
  echo '<li>' . _("delete a clinic user") . "</li>\n";
  echo "</ul>\n";

  echo "<hr />\n";

  echo '<h2 class="icon dumpIcon">' . HTML::strLink(_("Dumps"), '../admin/dump_view_form.php') . "</h2>\n";
  echo '<p>' . _("From this option you can:") . "</p>\n";

  echo "<ul>\n";
  echo '<li>' . _("install dump from file") . "</li>\n";
  echo '<li>' . sprintf(_("export database dump to %s format"), "MySQL") . "</li>\n";
  echo '<li>' . sprintf(_("export database dump to %s format"), "XML") . "</li>\n";
  echo '<li>' . sprintf(_("export database dump to %s format"), "CSV") . "</li>\n";
  echo '<li>' . _("optimize database") . "</li>\n";
  echo "</ul>\n";

  echo "<hr />\n";

  echo '<h2 class="icon logIcon">' . HTML::strLink(_("Logs"), '../admin/log_stats.php') . "</h2>\n";
  echo '<p>' . _("View logs generated by the program:") . "</p>\n";

  echo "<ul>\n";
  echo '<li>' . _("user's accesses logs") . "</li>\n";
  echo '<li>' . _("operations with medical records logs") . "</li>\n";
  echo '<li>' . _("statistics for years, months, days and hours") . "</li>\n";
  echo "</ul>\n";

  require_once("../shared/footer.php");
?>
